#ifndef SHAREDLIBRARYDEFINE_H
#define SHAREDLIBRARYDEFINE_H

#ifdef _WIN32_
    #ifdef ENABLE_SHARED_LIBRARY
    #  define SHAREDLIBRARYDEFINE_EXPORT Q_DECL_EXPORT
    #else
    #  define SHAREDLIBRARYDEFINE_EXPORT Q_DECL_IMPORT
    #endif
#else
    # define SHAREDLIBRARYDEFINE_EXPORT
#endif

#define _MYNAMESPACE_ MyMPI

#endif // SHAREDLIBRARYDEFINE_H

